### ISSUE TITLE
Emulator rendering issues in Google Chrome

### ISSUE THREAD

**Issue by Titanic4** [neophob/wpc-emu#76] opened 2021-01-20 10:44 UTC
![Capture](https://user-images.githubusercontent.com/1963921/105163414-2c8f6280-5b14-11eb-8485-f7c2c80cd528.PNG)
The emulator gives Hall of Mirrors effect while it's running, as seen on the provided screenshot. That's most noticeable when scrolling, or when DMD is updating. The issue doesn't occur in Mozilla Firefox on the same system.
Chrome version: 88.0.4324.96
OS: Windows 10 Home Version 2004 build 19041.685

**Comment by neophob** [comment] 2021-01-20 12:42
Thanks for the report.. this fancy effect is visible all the time or only temporary?

**Comment by Titanic4** [comment] 2021-01-20 16:12
This effect seems to happen every time I open the website on affected browser. The effect is visible all the time.

**Comment by mars-low** [comment] 2022-02-08 11:30
It is a bug in Chrome that can be tracked here:  https://bugs.chromium.org/p/chromium/issues/detail?id=1294557. On Linux canvas becomes transparent so you can see your desktop background behind controls. On Android and Windows it causes additional rendering issues.

Basically it is caused by combo in this two lines:
https://github.com/neophob/wpc-emu/blob/a8de4bc8bc92689930a36935cb7fb9326c920327/client/scripts/ui/oblivion-ui.js#L355
https://github.com/neophob/wpc-emu/blob/a8de4bc8bc92689930a36935cb7fb9326c920327/client/scripts/ui/oblivion-ui.js#L397

Calling `getContext` with `{alpha: false}` and then `clear` on this context causes this issue.  Removing explicit `{alpha: false}` should fix a problem.

**Comment by neophob** [comment] 2022-02-08 14:06
thanks @mars-low for the solution. afaik I added that alpha: false as optimisation - but i think that should not be an issue..

**Comment by neophob** [comment] 2022-02-22 16:55
fixed in v0.36.8

**Closed** 2022-02-22 16:55 UTC
